services:
  - docker

before_install:
  - docker pull ubuntu:trusty

script:
  - docker build -t bitbayofficial/builder-linux64:alpine . -f trusty.dockerfile

deploy:
  provider: script
  script: sh "./deploy.sh"
  on:
    branch: master

