services:
  - docker

before_install:
  - docker pull alpine:3.8

script:
  - docker build -t bitbayofficial/builder-linux64:alpine . -f alpine.dockerfile

deploy:
  provider: script
  script: sh "./deploy.sh"
  on:
    branch: master

